### ISSUE TITLE
Trigger issue, with the latest update 0.7.5

### ISSUE THREAD

**Issue by cipherlogs** [k0kubun/xremap#154]
```
keymap:
  - name: Global
    remap:
      WIN-k: up
      WIN-j: down
      WIN-l: right
      WIN-h: left
      j:
        remap:
          k: Esc
          l: C-space
        timeout_millis: 100
```

I have been using this config for so long with no problems, but the latest update broke everything.

first now if I hit a combination so fast for example j-> s I will get `sj` which is not right.

second if for example I press a combination where it contains `Win-k` or `Win-j` etc ...
it will trigger them ??

`shift + win + k` will trigger `Win - k`
`ctrl + win + k` will trigger `win - k`

**Comment by cipherlogs** [comment]
no worries, I have already rolled back to the latest working version.
v0.5.3.

wish you all the best, once you have time I'll be here :)

**Comment by k0kubun** [comment]
Fixed in v0.7.7.

**Comment by cipherlogs** [comment]
Hello, I did update to 0.7.7.1

first issue I have stated was

`if I hit a combination so fast for example j-> s I will get sj which is not right.`

it is now fixed

second issue

```
shift + win + k will trigger Win - k
ctrl + win + k will trigger win - k
```

this one is not fixed

**Comment by k0kubun** [comment]
Can you file another issue for the second case? Also, please write the expected behavior in that issue.
